services:
  cloppus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - cloppi
    volumes:
      - .:/app
    env_file: .env
  cloppi:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cloppi
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
  migrate:
    image: migrate/migrate
    depends_on:
      - cloppi
    environment:
      DB_URL: ${DB_URL}
    entrypoint: ["sh", "-c", "migrate -path /migrations -database ${DB_URL} up"]
    volumes:
      - ./db/migrations:/migrations

volumes:
  db_data:
