// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const authenticateUser = `-- name: AuthenticateUser :exec
UPDATE users
  SET auth = true
  WHERE id = $1
`

func (q *Queries) AuthenticateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, authenticateUser, id)
	return err
}
