// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_user.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
  username, email, auth , hash
) VALUES ( $1, $2 ,$3 ,$4 )
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Auth     bool   `json:"auth"`
	Hash     string `json:"hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Auth,
		arg.Hash,
	)
	return err
}
