// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: like_message.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const likeMessage = `-- name: LikeMessage :exec
UPDATE messages
  SET likes = likes + 1
  WHERE id = $1
`

func (q *Queries) LikeMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, likeMessage, id)
	return err
}
