// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: list_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const listUser = `-- name: ListUser :one
SELECT id, username, email, created_at, updated_at, deleted_at
  FROM users
  WHERE id = $1
`

func (q *Queries) ListUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, listUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
