// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: list_messages.sql

package repository

import (
	"context"
)

const listMessages = `-- name: ListMessages :many
SELECT id, owner, subject, content, likes, created_at, updated_at, deleted_at
  FROM messages
  WHERE owner = $1
`

func (q *Queries) ListMessages(ctx context.Context, owner string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Subject,
			&i.Content,
			&i.Likes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
