// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_message.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
  SET subject = $3,
  content = $4,
  updated_at = CURRENT_TIMESTAMP
  WHERE id = $1 AND owner = $2
  RETURNING id, owner, subject, content, likes, created_at, updated_at
`

type UpdateMessageParams struct {
	ID      uuid.UUID `json:"id"`
	Owner   string    `json:"owner"`
	Subject string    `json:"subject"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage,
		arg.ID,
		arg.Owner,
		arg.Subject,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Subject,
		&i.Content,
		&i.Likes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
