// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_user.sql

package repository

import (
	"context"
)

const updateUser = `-- name: UpdateUser :exec
INSERT INTO users (
  username, email, hash
) VALUES ( $1, $2 ,$3 )
`

type UpdateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Hash     string `json:"hash"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Username, arg.Email, arg.Hash)
	return err
}
