// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_message.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
  SET subject = $2,
  content = $3
  WHERE id = $1
`

type UpdateMessageParams struct {
	ID      uuid.UUID `json:"id"`
	Subject string    `json:"subject"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Subject, arg.Content)
	return err
}
